### ISSUE TITLE
New language request!

### ISSUE THREAD

**Issue by DeskTecc** [sarhatabaot/FarmAssistReboot#28]
**Hello, i'm from Brazil and i want to help with translation of my native language, portuguese brazilian. 
The archive:**
[pt-br.zip](https://github.com/sarhatabaot/FarmAssistReboot/files/9833776/pt-br.zip)

(sorry for my bad english, i'm still learning)

**Thanks :)**

**Comment by sarhatabaot** [comment]
Thank you for the translation! Added via crowdin 👍
