### ISSUE TITLE
Error on placeholder

### ISSUE THREAD

**Issue by WarnDa** [sarhatabaot/FarmAssistReboot#63]
Hello,

The %farmassist_player_toggle% is "enabled" even if it's disabled.

The %farmassist_player_<uuid|name>% doesn't get this issue

**Comment by WarnDa** [comment]
Also your placeholderAPI aren't persistent, so after a /papi reload the placeholders stop working
It's an easy fix, just add a persist toggle : 
![image](https://github.com/sarhatabaot/FarmAssistReboot/assets/31826333/9c6d07be-b089-47c1-a911-f59265ad5eed)

https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/PlaceholderExpansion#full-example-2

**Comment by WarnDa** [comment]
Hello, it would be possible to release the update please ? :D

**Comment by sarhatabaot** [comment]
Update is on https://github.com/sarhatabaot/FarmAssistReboot/releases/tag/v1.4.2 :) 
Spigot / Modrinth etc coming soon.
