### ISSUE TITLE
Toggle "Latest Version" Message

### ISSUE THREAD

**Issue by 4rft5** [sarhatabaot/FarmAssistReboot#74]
I'm wondering if a command or toggle can be added to disable the "You are running the latest version" message upon joining a server.

**Comment by sarhatabaot** [comment]
You can achieve this by negating the `farmassist.notify.update` permission.

**Comment by sarhatabaot** [comment]
Opped users have all permissions. I don't know if there is a way to negate this, I guess I can add a simple toggle in the config file if you want to disable this outright.

**Comment by 4rft5** [comment]
> Opped users have all permissions. I don't know if there is a way to negate this, I guess I can add a simple toggle in the config file if you want to disable this outright.

That could work, maybe that toggle could still check for updates in the background on login and only notify if an update is available.

**Comment by sarhatabaot** [comment]
Implemented via a455a4b
